name: Workflow Monitor

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

permissions:
  issues: read
  discussions: read

jobs:
  monitor-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check Discussion vs Issue Activity
        uses: actions/github-script@v7
        with:
          script: |
            const oneWeekAgo = new Date();
            oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
            const since = oneWeekAgo.toISOString();
            
            // Get discussions created in the last week
            const discussions = await github.graphql(`
              query($owner: String!, $repo: String!, $since: DateTime!) {
                repository(owner: $owner, name: $repo) {
                  discussions(first: 100, orderBy: {field: CREATED_AT, direction: DESC}) {
                    nodes {
                      title
                      createdAt
                      category {
                        name
                        slug
                      }
                      comments(first: 1) {
                        totalCount
                      }
                    }
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              since: since
            });
            
            // Get issues created in the last week
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              since: since,
              state: 'all'
            });
            
            // Filter discussions created in the last week
            const recentDiscussions = discussions.repository.discussions.nodes.filter(
              d => new Date(d.createdAt) >= oneWeekAgo
            );
            
            // Generate report
            const report = "## Discussion-First Workflow Report\n\n" +
                          "**Period:** " + oneWeekAgo.toDateString() + " - " + new Date().toDateString() + "\n\n" +
                          "### Activity Summary:\n" +
                          "- **Discussions Created:** " + recentDiscussions.length + "\n" +
                          "- **Issues Created:** " + issues.data.length + "\n" +
                          "- **Conversion Ratio:** " + issues.data.length + "/" + recentDiscussions.length + " (" + ((issues.data.length / Math.max(recentDiscussions.length, 1)) * 100).toFixed(1) + "%)\n\n" +
                          "### Discussion Breakdown:\n" +
                          (recentDiscussions.map(d => "- **" + d.category.name + ":** " + d.title + " (" + d.comments.totalCount + " comments)").join('\n') || 'No discussions this week') + "\n\n" +
                          "### Issue Creation:\n" +
                          (issues.data.map(i => "- **" + i.title + "** (Created: " + new Date(i.created_at).toDateString() + ")").join('\n') || 'No direct issues created') + "\n\n" +
                          "### Health Indicators:\n" +
                          "- **Discussion Activity:** " + (recentDiscussions.length > 0 ? 'Active' : 'Low activity') + "\n" +
                          "- **Direct Issue Creation:** " + (issues.data.length === 0 ? 'Properly blocked' : issues.data.length + ' direct issues created') + "\n" +
                          "- **Community Engagement:** " + recentDiscussions.filter(d => d.comments.totalCount > 0).length + "/" + recentDiscussions.length + " discussions have responses\n\n" +
                          (issues.data.length > 0 ? "### Action Required:\nDirect issues were created this week. Check if:\n- Issue templates are properly disabled\n- Discussions redirects are working\n- Users are bypassing the workflow\n\n" : "") +
                          "---\n*This report is generated automatically to help monitor the discussion-first workflow effectiveness.*";
            
            console.log(report);
            
            // You could also create an issue or discussion with this report
            // For now, just log it to Actions output
